sshd_user: ansible
sshd_public_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIITcRRIbvsqEic860dA+E5aT3QRAJhS24G3+KEFgoVG8 project2-ansible
sshd_port: 22

#podman_username: ""
#podman_password: ""

nfs_ip: "172.16.0.2"

httpd_port: 8080

container_user: containers

TIMEZONE: "Europe/Belgrade"

